/**
 * Dummy initial dataset for in-memory and fallback operations
 */

const FALLBACK_CATEGORIES = [
  {
    id: "c1",
    name: "Elektronik",
    slug: "elektronik",
    description: "En yeni akıllı cihazlar, bilgisayarlar, kulaklıklar ve aksesuarlar.",
    icon: "cpu",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    productCount: 3,
  },
  {
    id: "c2",
    name: "Giyim & Moda",
    slug: "giyim-moda",
    description: "Trend giyim parçaları, çantalar ve günlük stil ürünleri.",
    icon: "shirt",
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    productCount: 1,
  },
  {
    id: "c3",
    name: "Spor & Outdoor",
    slug: "spor-outdoor",
    description: "Antrenman ekipmanları, termoslar ve outdoor malzemeleri.",
    icon: "activity",
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80",
    productCount: 1,
  },
  {
    id: "c4",
    name: "Ev & Yaşam",
    slug: "ev-yasam",
    description: "Evinizi güzelleştirecek modern dekorasyon ve yaşam çözümleri.",
    icon: "home",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80",
    productCount: 0,
  },
  {
    id: "c5",
    name: "Aksesuar",
    slug: "aksesuar",
    description: "Şıklığınızı tamamlayacak saat, gözlük ve takı koleksiyonları.",
    icon: "watch",
    imageUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80",
    productCount: 1,
  },
];

const FALLBACK_PRODUCTS = [
  {
    id: "p1",
    name: "Kablosuz ANC Kulak Üstü Kulaklık Pro",
    slug: "kablosuz-anc-kulak-ustu-kulaklik-pro",
    category: "Elektronik",
    categorySlug: "elektronik",
    price: 2499.0,
    oldPrice: 3199.0,
    discount: 22,
    rating: 4.8,
    reviewCount: 142,
    stock: 24,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    isFeatured: true,
    description: "Aktif gürültü engelleme (ANC), 40 saat pil ömrü, yüksek çözünürlüklü ses kalitesi ve ultra rahat hafızalı sünger yastıklar.",
  },
  {
    id: "p2",
    name: "Akıllı GPS Spor Saati V2",
    slug: "akilli-gps-spor-saati-v2",
    category: "Elektronik",
    categorySlug: "elektronik",
    price: 3899.0,
    oldPrice: 4500.0,
    discount: 13,
    rating: 4.9,
    reviewCount: 89,
    stock: 15,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
    isFeatured: true,
    description: "AMOLED ekran, nabız ve kandaki oksijen ölçümü, dahili GPS, 50m su geçirmezlik ve 14 gün pil ömrü ile kusursuz antrenman takibi.",
  },
  {
    id: "p3",
    name: "Minimalist Su Geçirmez Laptop Sırt Çantası",
    slug: "minimalist-su-gecirmez-laptop-sirt-cantasi",
    category: "Giyim & Moda",
    categorySlug: "giyim-moda",
    price: 1299.0,
    oldPrice: 1650.0,
    discount: 21,
    rating: 4.7,
    reviewCount: 64,
    stock: 40,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    isFeatured: true,
    description: "16 inç korumalı laptop bölmesi, su itici kumaş dokusu, ergonomik omuz askıları ve gizli hırsızlık önleyici pasaport cebi.",
  },
  {
    id: "p4",
    name: "Mekanik RGB Kompakt Klavye (%75)",
    slug: "mekanik-rgb-kompakt-klavye-75",
    category: "Elektronik",
    categorySlug: "elektronik",
    price: 1899.0,
    oldPrice: 2299.0,
    discount: 17,
    rating: 4.6,
    reviewCount: 110,
    stock: 18,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80",
    isFeatured: false,
    description: "Hot-swappable mekanik kırmızı anahtarlar, PBT tuş kapakları, alüminyum gövde ve kablosuz Bluetooth/2.4Ghz çoklu cihaz desteği.",
  },
  {
    id: "p5",
    name: "Ergonomik Yalıtımlı Çelik Termos (750ml)",
    slug: "ergonomik-yalitimli-celik-termos-750ml",
    category: "Spor & Outdoor",
    categorySlug: "spor-outdoor",
    price: 649.0,
    oldPrice: 799.0,
    discount: 18,
    rating: 4.8,
    reviewCount: 76,
    stock: 50,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80",
    isFeatured: false,
    description: "Çift duvarlı vakumlu 18/8 paslanmaz çelik, 24 saat soğuk ve 12 saat sıcak tutma performansı, sızdırmaz emniyetli kapak.",
  },
  {
    id: "p6",
    name: "Polarize Klasik Tasarım Güneş Gözlüğü",
    slug: "polarize-klasik-tasarim-gunes-gozlugu",
    category: "Aksesuar",
    categorySlug: "aksesuar",
    price: 899.0,
    oldPrice: 1150.0,
    discount: 22,
    rating: 4.5,
    reviewCount: 52,
    stock: 25,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80",
    isFeatured: false,
    description: "UV400 tam koruma filtreli polarize camlar, hafif asetat çerçeve, darbelere dayanıklı menteşe yapısı ve koruyucu deri kılıf.",
  },
];

module.exports = {
  FALLBACK_CATEGORIES,
  FALLBACK_PRODUCTS,
};
